# Generated by Django 5.2.17 on 2026-09-23 07:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=12, unique=True)),
                ('customer_name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('vehicle_make', models.CharField(max_length=40)),
                ('vehicle_model', models.CharField(max_length=60)),
                ('vehicle_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=15)),
                ('service_mode', models.CharField(choices=[('garage', "Garage visit"), ('doorstep', 'Doorstep service'), ('pickup', 'Pickup and drop')], default='garage', max_length=10)),
                ('address', models.TextField(blank=True)),
                ('scheduled_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('09-11', '9:00 AM - 11:00 AM'), ('11-13', '11:00 AM - 1:00 PM'), ('14-16', '2:00 PM - 4:00 PM'), ('16-18', '4:00 PM - 6:00 PM')], max_length=5)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=20)),
                ('speciality', models.CharField(blank=True, max_length=100)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_min', models.PositiveIntegerField(help_text='Rough starting price in INR')),
                ('price_max', models.PositiveIntegerField(help_text='Rough upper price in INR')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
