# Generated by Django 5.2.17 on 2026-09-23 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('chat', '0001_initial'),
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='booking',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='diagnosis.diagnosis'),
        ),
        migrations.AddField(
            model_name='booking',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.mechanic'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.service'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['scheduled_date', 'time_slot'], name='bookings_bo_schedul_7f3a18_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('mechanic', 'scheduled_date', 'time_slot'), name='one_active_booking_per_mechanic_slot'),
        ),
    ]
