# Generated by Django 5.2.17 on 2026-09-23 07:05

import chat.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('stage', models.CharField(choices=[('new', 'New'), ('gathering', 'Asking follow-up questions'), ('diagnosed', 'Diagnosed'), ('booked', 'Mechanic booked')], default='new', max_length=12)),
                ('issue_category', models.CharField(blank=True, max_length=40)),
                ('vehicle_make', models.CharField(blank=True, max_length=40)),
                ('vehicle_model', models.CharField(blank=True, max_length=60)),
                ('vehicle_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('odometer_km', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=12)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['client_id', '-updated_at'], name='chat_conver_client__085b7c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(db_index=True, max_length=64)),
                ('file', models.FileField(upload_to=chat.models.attachment_upload_path)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('checksum', models.CharField(db_index=True, help_text='sha256 of the file', max_length=64)),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Customer'), ('assistant', 'Mechanic bot')], max_length=10)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('question', 'Follow-up question'), ('diagnosis', 'Diagnosis'), ('rejection', 'Off-topic rejection'), ('booking_prompt', 'Booking prompt'), ('booking_confirmed', 'Booking confirmed'), ('error', 'Error')], default='text', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('quick_replies', models.JSONField(blank=True, default=list)),
                ('action', models.CharField(blank=True, max_length=30)),
                ('used_ai', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='bookings.booking')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
