# Generated by Django 5.2.17 on 2026-09-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ai_error',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
