# Generated by Django 5.2.17 on 2026-09-23 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_ai_error'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='customers.car'),
        ),
    ]
