# Generated by Django 5.2.17 on 2026-09-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('hinglish', 'Hinglish')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
