# Generated by Django 5.2.17 on 2026-09-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_conversation_language_message_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='registration_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
