# Generated by Django 5.2.17 on 2026-09-23 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=150)),
                ('summary', models.TextField()),
                ('probable_causes', models.JSONField(default=list)),
                ('severity', models.CharField(choices=[('low', 'Low - fix when convenient'), ('medium', 'Medium - get it checked soon'), ('high', 'High - avoid driving until checked'), ('critical', 'Critical - stop driving')], default='medium', max_length=10)),
                ('safe_to_drive', models.BooleanField(default=True)),
                ('advice', models.TextField(blank=True)),
                ('estimated_cost_min', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_cost_max', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('rules', 'Rule engine'), ('ai', 'Rule engine + Gemini')], default='rules', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='chat.conversation')),
                ('recommended_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses', to='bookings.service')),
            ],
            options={
                'verbose_name_plural': 'diagnoses',
                'ordering': ['-created_at'],
            },
        ),
    ]
